### ISSUE TITLE
License

### ISSUE THREAD

**Issue by platy** [davidmarkclements/quick-format#6]
Could you please provide a license. I am using quick-format and have just realised there is no license mentioned.

A repository link in package.json would also be appreciated.

#4 looks like a good option

**Comment by davidmarkclements** [comment]
my bad - take this comment that it's MIT licensed, and I'll come back and formalise as soon as I can

**Comment by platy** [comment]
Thanks David!

**Comment by davidmarkclements** [comment]
@platy done - sorry it took so long

**Comment by platy** [comment]
Thanks!
